# Generated by Django 5.0 on 2024-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
