# Generated by Django 5.0 on 2024-06-02 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0002_gallery_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 8, 7, 11, 521099, tzinfo=datetime.timezone.utc)),
        ),
    ]
