# Generated by Django 5.0 on 2024-06-20 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0004_alter_gallery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 23, 44, 32, 34261, tzinfo=datetime.timezone.utc)),
        ),
    ]
