# Generated by Django 5.0 on 2024-06-20 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0005_volunteerrequest_status_alter_gallery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 23, 44, 37, 292397, tzinfo=datetime.timezone.utc)),
        ),
    ]
