# Generated by Django 5.0 on 2024-09-20 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0006_alter_gallery_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='message',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 18, 24, 42, 477857, tzinfo=datetime.timezone.utc)),
        ),
    ]
