# Generated by Django 5.0 on 2024-09-24 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penciltruckadmin', '0008_otpinfo_alter_gallery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 14, 53, 51, 720622, tzinfo=datetime.timezone.utc)),
        ),
    ]
